name: Update Index

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    if: github.repository == 'kubernetes-sigs/downloadkubernetes'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: '1.23'
          check-latest: true

      - name: Update index
        run: make update-index

      - name: Check workspace
        id: create_pr
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo "create_pr=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        if: ${{ steps.create_pr.outputs.create_pr == 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update index
          title: 'Update index'
          body: >
            Update index
          labels: ok-to-test, feature, automated pr
          branch-suffix: timestamp
          branch: update-index
          delete-branch: true
